### ISSUE TITLE
When the training set is 50%, the experimental effect is far less than the paper effect. Right?

### ISSUE THREAD

**Issue by dbbice** [ahmedrashed-ml/GraphRec#4]
When I ran this code for the 100K data set, I found that the experimental results were similar to the results given in the paper when the training set was 90%, but when the training set was 50%, the results were much different. Do you do the same thing?My parameters are :ItemData=True,UserData=True,Graph=False,The RMSE obtained was 0.953 and the result in the paper was 0.923

**Comment by ahmedrashed-ml** [comment]
Hi,

Please have a look at section 5.8  in the paper to check the correct hyperparameters for the different configurations.

-For GraphRec 50% (w/o Graph Feat & w/ Side Feat) please use the below setup
`MFSIZE=40
UW=0.08
IW=0.06
LR=0.0002
EPOCH_MAX = 401
tf.reset_default_graph()
GraphRec(df_train, df_test,ItemData=True,UserData=True,Graph=False,Dataset='100k')
`
-For GraphRec 50%  (w/ Graph Feat & w/ Side Feat) please use the below setup
`MFSIZE=20
UW=0.05
IW=0.02
LR=0.00003
EPOCH_MAX = 322
tf.reset_default_graph()
GraphRec(df_train, df_test,ItemData=True,UserData=True,Graph=True,Dataset='100k')`

I also did a quick sanity check to make sure of those numbers are correct. There should be some fluctuation in the results because of the random initialization but its magnitude is usually very small

**Comment by dbbice** [comment]
> Hi,
> 
> Please have a look at section 5.8 in the paper to check the correct hyperparameters for the different configurations.
> 
> -For GraphRec 50% (w/o Graph Feat & w/ Side Feat) please use the below setup
> `MFSIZE=40 UW=0.08 IW=0.06 LR=0.0002 EPOCH_MAX = 401 tf.reset_default_graph() GraphRec(df_train, df_test,ItemData=True,UserData=True,Graph=False,Dataset='100k') `
> -For GraphRec 50% (w/ Graph Feat & w/ Side Feat) please use the below setup
> `MFSIZE=20 UW=0.05 IW=0.02 LR=0.00003 EPOCH_MAX = 322 tf.reset_default_graph() GraphRec(df_train, df_test,ItemData=True,UserData=True,Graph=True,Dataset='100k')`
> 
> I also did a quick sanity check to make sure of those numbers are correct. There should be some fluctuation in the results because of the random initialization but its magnitude is usually very small

Thank you for your reply. My problem has been solved. I'm sorry.
